services:
  web:
    image: nirgluzman/web:latest
    container_name: web
    build:
      context: . # path to a directory containing a Dockerfile
      dockerfile: Dockerfile.dev # sets an alternate Dockerfile
    ports:
      - 5000:3000
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app

  tests:
    depends_on:
      - web
    container_name: tests
    image: nirgluzman/web:latest
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app
    command: ["npm", "run", "test"]
