FROM node:lts-alpine3.20

# node user to execute all following commands, as opposed to root (default).
# https://docs.docker.com/reference/dockerfile/#user
# by default, Docker uses the root user to perform all the tasks but for security purposes, we're making a separate user that handles the further tasks.
USER node

RUN mkdir -p /home/node/app
WORKDIR /home/node/app

# Docker doesn't support COPY as a user other than root; we need to chown / chmod the file after the COPY command.
COPY --chown=node:node ./package.json .
RUN npm install

COPY --chown=node:node . .

CMD ["npm", "start"]
