# Beanstalk Deploy, https://github.com/marketplace/actions/beanstalk-deploy
# https://aws.amazon.com/blogs/security/use-iam-roles-to-connect-github-actions-to-actions-in-aws/

name: Deploy React to AWS Elastic Beanstalk
on:
  workflow_dispatch:
  push:

env:
  DEV_IMAGE: nirgluzman/dev:latest
  PROD_IMAGE: nirgluzman/docker-react:latest
  AWS_REGION: us-east-1
  AWS_ROLE: ${{ secretes.AWS_ROLE }}

# Permission can be added at job level or workflow level
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    # - name: Login to Docker Hub
    #   uses: docker/login-action@v3
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}

    # - name: Build dev image
    #   run: docker build -t ${{ env.DEV_IMAGE }} -f Dockerfile.dev .

    # # By default `npm run test` runs the watcher with interactive CLI.
    # # However, we can force it to run tests once and finish the process by setting the CI environment variable.
    # - name: Run tests
    #   run: docker run -e CI=true ${{ env.DEV_IMAGE }} npm run test -- --coverage

    - name: Configure aws credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ env.AWS_ROLE}}
        aws-region: ${{ env.AWS_REGION }}

    # Hello from AWS: WhoAmI
    - name: Sts GetCallerIdentity
      run: |
        aws sts get-caller-identity
